services:
  extract:
    build: .
    container_name: crypto-etl-extract
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:16
    container_name: postgresSQL
    volumes:
      - ./data:/app/data

  airflow-init:

  airflow-webserver:

  airflow-scheduler:

